name: "Provision AGIC"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/agic_extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Use your preferred version
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

        
